# Generated by Django 5.2.3 on 2025-10-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportHub', '0003_userprofile_profile_picture_complaintreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='complaintreport',
            name='report_details',
        ),
        migrations.AddField(
            model_name='complaintreport',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='complaintreport',
            name='report_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
