# Generated by Django 5.2.3 on 2025-10-22 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportHub', '0004_remove_complaintreport_generated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SupportHub.complaint'),
        ),
    ]
